services:
  postgres:
    image: postgres:16
    container_name: pg-holidays
    environment:
      POSTGRES_DB: holidaysdb
      POSTGRES_USER: holidays
      POSTGRES_PASSWORD: holidays
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U holidays -d holidaysdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: holidays-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/holidaysdb
      SPRING_DATASOURCE_USERNAME: holidays
      SPRING_DATASOURCE_PASSWORD: holidays

volumes:
  pgdata:
